spring:
  application:
    name: users


mongo:
  conn:
    host: my-cluster.xksc7jt.mongodb.net
    port: ${DB_PORT}
    database: ${DB_NAME}
    user: ${DB_USER}
    password: ${DB_PASSWORD}

logging:
  level:
    org.springframework.security: DEBUG

server:
  port: 8081

jwt:
  private-key-path: ${PRIVATE_KEY_PATH}
  public-key-path: ${PUBLIC_KEY_PATH}
